export type Site = { id: string; name: string; country: string; region: string; rank: number; notes: string | null; reference: string | null; coordinates: [number, number] };
export type Story = { title: string; art: string; period: string; dates: string; heading: string; description: string; highlight: string; source: string; sourceLabel: string };
export const BASE = '/maya';
export const normalize = (text: string) => text.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase();
export const rankName = (rank: number) => ({1:'Major centre',2:'Important site',3:'Medium site',4:'Minor site',5:'Minimal remains'}[rank] || 'Unclassified');
export const stories: Record<string, Story> = {
 'Chichen Itza': { title: 'Chichén Itzá', art: 'chichen-itza', period: 'Classic · Postclassic', dates: '6th–15th centuries CE', heading: 'A city written in stone', description: 'At the heart of the northern Yucatán, Chichén Itzá grew into one of the great centres of the Maya world. Its architecture brings local Maya traditions into conversation with influences from central Mexico. El Castillo rises above plazas, colonnades and a monumental ball court.', highlight: 'El Castillo · Great Ball Court · El Caracol', source: 'https://whc.unesco.org/en/list/483/', sourceLabel: 'UNESCO World Heritage Centre' },
 'Tikal': { title: 'Tikal', art: 'tikal', period: 'Preclassic · Classic', dates: '6th century BCE–10th century CE', heading: 'Above the forest canopy', description: 'Deep in Guatemala’s Petén forest, Tikal’s steep temples rise above a city of palaces, plazas and reservoirs. A major political and economic centre, it connected with cities across Mesoamerica. Thousands of architectural remains extend into the surrounding forest.', highlight: 'Great Plaza · Temple I · Lost World complex', source: 'https://whc.unesco.org/en/list/64/', sourceLabel: 'UNESCO World Heritage Centre' },
 'Palenque': { title: 'Palenque', art: 'palenque', period: 'Classic', dates: 'Peak: 6th–8th centuries CE', heading: 'Stone, water and memory', description: 'At the foot of the Chiapas highlands, Palenque brings finely proportioned temples and palaces into a green, wooded landscape. Its sculpted reliefs and inscriptions preserve an exceptional record of Maya art and royal history. The Temple of the Inscriptions is among its defining monuments.', highlight: 'Temple of the Inscriptions · Palace · carved reliefs', source: 'https://whc.unesco.org/en/list/411/', sourceLabel: 'UNESCO World Heritage Centre' },
 'Uxmal': { title: 'Uxmal', art: 'uxmal', period: 'Late Classic', dates: 'Peak: 9th–10th centuries CE', heading: 'The geometry of the Puuc', description: 'Uxmal’s buildings are arranged across the low hills of the Puuc region. Long, carefully proportioned façades carry intricate stone mosaics, while the Pyramid of the Magician gives the city its distinctive silhouette. Its ceremonial architecture reflects a sophisticated understanding of space and ornament.', highlight: 'Pyramid of the Magician · Nunnery Quadrangle', source: 'https://whc.unesco.org/en/list/791/', sourceLabel: 'UNESCO World Heritage Centre' },
 'Copan': { title: 'Copán', art: 'copan', period: 'Classic', dates: 'Peak: 300–900 CE', heading: 'A dynasty carved in stone', description: 'In the Copán Valley of western Honduras, sculpted stelae and altars give remarkable form to Maya royal history. Plazas and an elevated Acropolis form the heart of the city. The Hieroglyphic Stairway preserves an exceptionally long inscription from the Maya world.', highlight: 'Sculpted stelae · Acropolis · Hieroglyphic Stairway', source: 'https://whc.unesco.org/en/list/129/', sourceLabel: 'UNESCO World Heritage Centre' },
 'Tulum': { title: 'Tulum', art: 'tulum', period: 'Postclassic', dates: 'Visible buildings: 1250–1550 CE', heading: 'Where the city meets the sea', description: 'Overlooking the Caribbean, Tulum occupies a striking coastal position in Quintana Roo. Most of its visible buildings belong to the later centuries of pre-Hispanic occupation, although earlier remains point to a longer history. Its compact temples stand within one of the Maya world’s best-known coastal settlements.', highlight: 'Coastal temples · walled settlement · Caribbean setting', source: 'https://lugares.inah.gob.mx/es/node/4361', sourceLabel: 'Instituto Nacional de Antropología e Historia' },
};
export const featuredNames = ['Chichen Itza','Tikal','Palenque','Uxmal','Copan','Tulum'];
export const titleFor = (site: Site) => stories[site.name]?.title || site.name;
export function artFor(site: Site) { return stories[site.name]?.art || (site.coordinates[1] < 16 ? 'highlands' : 'lowlands'); }
export function geojson(sites: Site[]) { return { type: 'FeatureCollection' as const, features: sites.map(site => ({type:'Feature' as const, id:site.id, geometry:{ type:'Point' as const,coordinates:site.coordinates }, properties:{ id:site.id,name:titleFor(site),rank:site.rank } })) }; }
export function findSites(sites: Site[], query: string) { const term=normalize(query.trim()); return sites.filter(s => normalize(`${s.name} ${titleFor(s)} ${s.region} ${s.country}`).includes(term)); }
